#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            providerClass: PersistedUsernamePasswordProvider
            entryPoint:
              WebRedirect:
                uri: admin/authentication

  Blog:
    notifications:
      to:
        email: ''
        name: 'Blog Admin'
