#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            providerClass: PersistedUsernamePasswordProvider
            entryPoint:
              WebRedirect:
                uri: admin/authentication

  Blog:
    notifications:
      to:
        email: 'apocalip@gmail.com'
        name: 'Blog Admin'

Admin:
  Beings:
    TYPO3\Blog\Domain\Model\Comment:
      Properties:
        author:
          Label: Author
        emailAddress:
          Label: E-Mail
          Infotext: The E-Mail will not be publicly displayed
        content:
          Widget: Textarea